version: '3.8'
services:
  broker:
    image: apachepulsar/pulsar:3.0.0
    container_name: broker
    command: bin/pulsar broker
    environment:
      - PULSAR_MEM="-Xms128m -Xmx128m -XX:MaxDirectMemorySize=128m"  # Further reduced memory allocation
    ports:
      - "6650:6650"
      - "8080:8080"
    volumes:
      - broker-data:/pulsar/data
      - broker-config:/pulsar/conf"

  pulsar-manager:
    image: apachepulsar/pulsar-manager:v0.3.0
    container_name: pulsar-manager
    ports:
      - "9527:9527"
      - "7750:7750"
    environment:
      - SPRING_CONFIGURATION_FILE=/pulsar-manager/pulsar-manager/application.properties
    depends_on:
      - broker

volumes:
  broker-data:
  broker-config:
